### ISSUE TITLE
Expected media queries 

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/hide-show-responsively#1]
I was able to complete the exercise in my own way and match the screenshots but Markbot expects to see `<.dino-wrap>` selector (I believe in smallest media size) and `<.dino>` selector in the 25em, 38em and 60em media queries. I couldn't figure out and am really curious about the way these selectors are used. Thank you.

@thomasjbradley

**Comment by thomasjbradley** [comment]
The way I solved it was to use `.dino { display: flex }` outside media queries. Then just control the widths of the `.dino-wrap` within each MQ.

**Comment by C-G-G** [comment]
May I ask how you control the widths of the `.dino-wrap` within each MQ after using `.dino { display: flex }`? Just give it a particular % or em?

**Comment by C-G-G** [comment]
Thank you, it's all good now except one small thing: Markbot expects to see `.dino` selector in the `@38em` and `@60em` media queries. Not sure if it matters (looks/works fine) but wondering if I'm forgetting something important there.

@thomasjbradley

**Comment by thomasjbradley** [comment]
I’m using the `.dino` selector to change the widths of the dinosaur images boxes in each media query, using percentages.
